# Generated by Django 4.0.2 on 2022-02-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atikcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atikname', models.CharField(max_length=10)),
                ('atik_features', models.TextField(max_length=60)),
                ('where_to_go', models.TextField(max_length=50)),
                ('atik_advice', models.TextField(max_length=100)),
                ('klavuz', models.CharField(max_length=30)),
            ],
        ),
    ]
