# Generated by Django 4.0.2 on 2022-03-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0004_remove_atikcodes_atik_advice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atikcodes',
            name='list2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
