# Generated by Django 4.0.2 on 2022-03-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0005_atikcodes_list2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atiktypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlname', models.CharField(max_length=50)),
                ('whatIsIt', models.TextField(max_length=500)),
                ('whyİmportant', models.TextField(max_length=500)),
                ('whereAccours', models.TextField(max_length=500)),
                ('howUnderstand', models.TextField(max_length=700)),
                ('mainname', models.CharField(max_length=50)),
            ],
        ),
    ]
