# Generated by Django 4.0.2 on 2022-04-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0006_atiktypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtiktypesCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlName', models.CharField(help_text='ait olduğu atık türü', max_length=50)),
                ('itsMaintitle', models.CharField(help_text='atık türünün ana başlığı örn 04 some text', max_length=100)),
                ('itsMiddleTitle', models.CharField(help_text='atık türünün orta başlığı örn. 04.42 some text', max_length=100)),
                ('itself', models.CharField(help_text='atık türünün alt başlığı örn. 04.02.01 some text', max_length=100)),
            ],
        ),
    ]
