# Generated by Django 4.0.2 on 2022-04-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0007_atiktypescodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='firstSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upperMark', models.CharField(help_text='örn. tıbbi atık', max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('selfMark', models.CharField(help_text='örn. 04', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='secondSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upperMark', models.CharField(help_text='örn. 04', max_length=50)),
                ('content', models.TextField(max_length=200)),
                ('selfMark', models.CharField(help_text='örn. 04-01', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='thirdSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upperMark', models.CharField(help_text='örn. 04-01', max_length=50)),
                ('content', models.TextField(max_length=300)),
                ('selfMark', models.CharField(help_text='örn. 04-01-01', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='AtiktypesCodes',
        ),
    ]
