# Generated by Django 4.0.1 on 2022-04-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0008_firststeps_secondsteps_thirdsteps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdsteps',
            name='href',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='atiktypes',
            name='howUnderstand',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='atiktypes',
            name='whatIsIt',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='atiktypes',
            name='whereAccours',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='atiktypes',
            name='whyİmportant',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='firststeps',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
