# Generated by Django 4.0.2 on 2022-05-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0009_thirdsteps_href_alter_atiktypes_howunderstand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='buttonPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainName', models.CharField(max_length=100)),
                ('prosesFeatures', models.TextField(max_length=1000)),
                ('urlName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='olusabilecek_diger_atıklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upperMark', models.CharField(help_text='metalmadenciligi', max_length=100)),
                ('selfMark', models.CharField(help_text='01-01-01', max_length=100)),
                ('selfContent', models.TextField(max_length=350)),
            ],
        ),
        migrations.CreateModel(
            name='prosesKaynaklıAtıklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upperMark', models.CharField(help_text='metalmadenciligi', max_length=100)),
                ('selfMark', models.CharField(help_text='01-01-01', max_length=100)),
                ('selfContent', models.TextField(max_length=350)),
            ],
        ),
    ]
