# Generated by Django 4.0.2 on 2022-05-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0010_buttonpart_olusabilecek_diger_atıklar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonpart',
            name='atikoneri',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='buttonpart',
            name='files',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='buttonpart',
            name='nace',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
