# Generated by Django 4.0.2 on 2022-05-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0011_buttonpart_atikoneri_buttonpart_files_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='olusabilecek_diger_atıklar',
        ),
        migrations.DeleteModel(
            name='prosesKaynaklıAtıklar',
        ),
        migrations.AddField(
            model_name='buttonpart',
            name='olusabilecek_diger',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='buttonpart',
            name='prosesKaynakli',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
