# Generated by Django 4.0.2 on 2022-07-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='atikcodes',
            name='itsId',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
