# Generated by Django 4.0.2 on 2022-07-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0014_atikcodes_itsid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atikcodes',
            name='howDefineContent',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='howToReduceContent',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='img',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='itsId',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='itsTtile',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='itsType',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='legislationlistContent',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='list1',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='list2',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='warningContent',
        ),
        migrations.RemoveField(
            model_name='atikcodes',
            name='whereAccoursContent',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='bioprocessability',
            field=models.CharField(help_text='0-5 arası bir değerle puanlandırın', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='file1',
            field=models.FileField(help_text='Bu atık; atık tesisine nasıl taşınmalıdır ?', null=b'I01\n', upload_to=''),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='file2',
            field=models.FileField(help_text='Bu atık; atık tesisine nasıl taşınmalıdır ?', null=b'I01\n', upload_to=''),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='flammability',
            field=models.CharField(help_text='0-5 arası bir değerle puanlandırın', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='howAccumulate',
            field=models.TextField(help_text='Bu atık nasıl kaynağında azaltılabilir?', max_length=700, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='howDefine',
            field=models.TextField(help_text='Bu koda sahip atıkları nasıl tanımlarız?', max_length=700, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='howReduce',
            field=models.TextField(help_text='Bu atık nasıl kaynağında azaltılabilir?', max_length=700, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='id denemesi',
            field=models.CharField(help_text='örn. 3', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='itsUpTitle',
            field=models.CharField(help_text='örn. Tıbbi atık', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='legislation1',
            field=models.TextField(help_text='Bu atık hangi mevzuatla ilişkilidir(1)', max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='legislation2',
            field=models.TextField(help_text='Bu atık hangi mevzuatla ilişkilidir(2)', max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='materialRecycling',
            field=models.CharField(help_text='0-5 arası bir değerle puanlandırın', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='secondImage',
            field=models.ImageField(null=b'I01\n', upload_to=''),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='warningMessage',
            field=models.TextField(help_text='uyarı mesajı(1)', max_length=700, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='warningMessage2',
            field=models.TextField(help_text='uyarı mesajı(2)', max_length=700, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='wasteType',
            field=models.CharField(help_text='tehlikeli = 1, tehlikesiz = 2, uygun kodu seçiniz.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='whereAccur',
            field=models.TextField(help_text='bu koda sahip atıklar nerde oluşur?', max_length=700, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
