# Generated by Django 4.0.2 on 2022-07-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0015_remove_atikcodes_howdefinecontent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atikcodes',
            old_name='itsUpTitle',
            new_name='Ait oldugu atık türü',
        ),
        migrations.RenameField(
            model_name='atikcodes',
            old_name='id denemesi',
            new_name='Id numarası',
        ),
        migrations.RenameField(
            model_name='atikcodes',
            old_name='wasteType',
            new_name='Uygun kodu seçiniz',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='firstImage',
            field=models.ImageField(null=b'I01\n', upload_to=''),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='inBox',
            field=models.TextField(help_text='uyarı yazısı', max_length=700, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
