# Generated by Django 4.0.2 on 2022-07-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0016_rename_itsuptitle_atikcodes_ait oldugu atık türü_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atikcodes',
            name='Id numarası',
            field=models.CharField(default='', help_text='örn. 3', max_length=10),
        ),
    ]
