# Generated by Django 4.0.2 on 2022-07-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0017_alter_atikcodes_id numarası'),
    ]

    operations = [
        migrations.AddField(
            model_name='atikcodes',
            name='Atığın adı',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='Ait oldugu atık türü',
            field=models.CharField(default='', help_text='örn. Tıbbi atık', max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='Uygun kodu seçiniz',
            field=models.CharField(default='', help_text='tehlikeli = 1, tehlikesiz = 2, uygun kodu seçiniz.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='bioprocessability',
            field=models.CharField(default='', help_text='0-5 arası bir değerle puanlandırın', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='file1',
            field=models.FileField(default='', help_text='Bu atık; atık tesisine nasıl taşınmalıdır ?', null=b'I01\n', upload_to=''),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='file2',
            field=models.FileField(default='', help_text='Bu atık; atık tesisine nasıl taşınmalıdır ?', null=b'I01\n', upload_to=''),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='firstImage',
            field=models.ImageField(default='', null=b'I01\n', upload_to=''),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='flammability',
            field=models.CharField(default='', help_text='0-5 arası bir değerle puanlandırın', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='howAccumulate',
            field=models.TextField(default='', help_text='Bu atık nasıl kaynağında azaltılabilir?', max_length=700, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='howDefine',
            field=models.TextField(default='', help_text='Bu koda sahip atıkları nasıl tanımlarız?', max_length=700, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='howReduce',
            field=models.TextField(default='', help_text='Bu atık nasıl kaynağında azaltılabilir?', max_length=700, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='inBox',
            field=models.TextField(default='', help_text='uyarı yazısı', max_length=700, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='legislation1',
            field=models.TextField(default='', help_text='Bu atık hangi mevzuatla ilişkilidir(1)', max_length=100, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='legislation2',
            field=models.TextField(default='', help_text='Bu atık hangi mevzuatla ilişkilidir(2)', max_length=100, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='materialRecycling',
            field=models.CharField(default='', help_text='0-5 arası bir değerle puanlandırın', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='secondImage',
            field=models.ImageField(default='', null=b'I01\n', upload_to=''),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='warningMessage',
            field=models.TextField(default='', help_text='uyarı mesajı(1)', max_length=700, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='warningMessage2',
            field=models.TextField(default='', help_text='uyarı mesajı(2)', max_length=700, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='atikcodes',
            name='whereAccur',
            field=models.TextField(default='', help_text='bu koda sahip atıklar nerde oluşur?', max_length=700, null=b'I01\n'),
        ),
    ]
