# Generated by Django 4.0.2 on 2022-07-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0018_atikcodes_atığın adı_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atikcodes',
            name='Atığın adı',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
