# Generated by Django 4.0.2 on 2022-07-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0019_alter_atikcodes_atığın adı'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atikcodes',
            name='Atığın adı',
        ),
        migrations.AddField(
            model_name='atikcodes',
            name='Atık ismi',
            field=models.CharField(default='', max_length=70, null=True),
        ),
    ]
