# Generated by Django 4.0.2 on 2022-07-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0021_alter_atikcodes_ait oldugu atık türü'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atikcodes',
            name='howDefine',
            field=models.TextField(help_text='Bu koda sahip atıkları nasıl tanımlarız?', max_length=700, null=b'I01\n'),
        ),
    ]
