# Generated by Django 4.0.2 on 2022-07-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0022_alter_atikcodes_howdefine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atikcodes',
            old_name='Id numarası',
            new_name='idNo',
        ),
    ]
