# Generated by Django 4.0.2 on 2022-07-03 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0023_rename_id numarası_atikcodes_idno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atikcodes',
            new_name='Atikcodes2',
        ),
    ]
