# Generated by Django 4.0.2 on 2022-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0026_buttonpart_olusabilecek_digerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atiktypes',
            name='howUnderstand',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='atiktypes',
            name='whatIsIt',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='atiktypes',
            name='whereAccours',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='atiktypes',
            name='whyİmportant',
            field=models.TextField(max_length=2000),
        ),
    ]
