# Generated by Django 4.0.1 on 2022-09-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0027_alter_atiktypes_howunderstand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atiktypes',
            name='howUnderstand',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='atiktypes',
            name='whatIsIt',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='atiktypes',
            name='whereAccours',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='atiktypes',
            name='whyİmportant',
            field=models.TextField(max_length=3000),
        ),
    ]
