# Generated by Django 4.0.1 on 2022-09-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutuphane', '0028_alter_atiktypes_howunderstand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atiktypes',
            old_name='whyİmportant',
            new_name='whyImportant',
        ),
    ]
